# Generated by Django 5.1.1 on 2024-10-02 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='total_marks',
            field=models.PositiveIntegerField(default=0, verbose_name='Суммарная оценка'),
        ),
        migrations.AddField(
            model_name='cat',
            name='total_votes',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество голосовавших'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='show.cat'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.PositiveSmallIntegerField(verbose_name='Оценка'),
        ),
    ]
